"""align member fields and session user_id

Revision ID: 1df292a72279
Revises: fe0a4cf8ae32
Create Date: 2026-09-02 07:45:52.854882
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = '1df292a72279'
down_revision = 'fe0a4cf8ae32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('unionid', sa.String(length=64), nullable=True, comment='微信 unionid（多端绑定预留）'))
    op.add_column('member', sa.Column('gender', sa.Integer(), nullable=False, comment='0 未知 / 1 男 / 2 女'))
    op.add_column('member', sa.Column('member_level', sa.String(length=20), nullable=False, comment='会员等级 bronze/silver/gold/platinum'))
    op.add_column('member', sa.Column('points', sa.Integer(), nullable=False, comment='当前积分'))
    op.add_column('member', sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最近登录时间'))
    op.alter_column('member', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=512),
               existing_comment='头像 URL',
               existing_nullable=True)
    op.create_index(op.f('ix_member_phone'), 'member', ['phone'], unique=False)
    op.add_column('member_session', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('member_session_ibfk_1', 'member_session', type_='foreignkey')
    op.drop_index('ix_member_session_member_id', table_name='member_session')
    op.create_index(op.f('ix_member_session_user_id'), 'member_session', ['user_id'], unique=False)
    op.create_foreign_key(None, 'member_session', 'member', ['user_id'], ['id'])
    op.drop_column('member_session', 'member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_session', sa.Column('member_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'member_session', type_='foreignkey')
    op.create_foreign_key('member_session_ibfk_1', 'member_session', 'member', ['member_id'], ['id'])
    op.drop_index(op.f('ix_member_session_user_id'), table_name='member_session')
    op.create_index('ix_member_session_member_id', 'member_session', ['member_id'], unique=False)
    op.drop_column('member_session', 'user_id')
    op.drop_index(op.f('ix_member_phone'), table_name='member')
    op.alter_column('member', 'avatar',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_comment='头像 URL',
               existing_nullable=True)
    op.drop_column('member', 'last_login_at')
    op.drop_column('member', 'points')
    op.drop_column('member', 'member_level')
    op.drop_column('member', 'gender')
    op.drop_column('member', 'unionid')
    # ### end Alembic commands ###
