"""init member and member_session

Revision ID: fe0a4cf8ae32
Revises: 
Create Date: 2026-09-02 07:36:08.478415
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'fe0a4cf8ae32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('openid', sa.String(length=64), nullable=False, comment='微信 openid'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像 URL'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态：1 正常 0 禁用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='逻辑删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_openid'), 'member', ['openid'], unique=True)
    op.create_table('member_session',
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False, comment='不透明 token'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='逻辑删除标记'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_session_member_id'), 'member_session', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_session_token'), 'member_session', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_session_token'), table_name='member_session')
    op.drop_index(op.f('ix_member_session_member_id'), table_name='member_session')
    op.drop_table('member_session')
    op.drop_index(op.f('ix_member_openid'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
